# Generated by Django 5.2.6 on 2025-11-13 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=60, verbose_name='Complemento')),
                ('district', models.CharField(max_length=80, verbose_name='Bairro')),
                ('city_name', models.CharField(max_length=120, verbose_name='Cidade')),
                ('city_ibge_code', models.CharField(help_text='Código IBGE (7 dígitos)', max_length=7, verbose_name='Código IBGE')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('postal_code', models.CharField(help_text='CEP (8 dígitos)', max_length=8, verbose_name='CEP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'indexes': [models.Index(fields=['city_ibge_code'], name='core_addres_city_ib_4874d2_idx'), models.Index(fields=['state'], name='core_addres_state_58f97a_idx')],
            },
        ),
    ]
