# Generated by Django 5.2.6 on 2025-10-15 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_establishment_environment_default'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo ou inativo.', verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('trading_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cpf_cnpj', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo de Pessoa')),
                ('partner_type', models.CharField(blank=True, choices=[('customer', 'Cliente'), ('supplier', 'Fornecedor')], max_length=10, null=True, verbose_name='Tipo de Parceiro')),
                ('tax_regime', models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('simples_excesso', 'Simples Nacional – Excesso sublimite'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=20, null=True, verbose_name='Regime Tributário')),
                ('tax_payer_type', models.CharField(blank=True, choices=[('non_taxpayer', 'Não Contribuinte'), ('taxpayer', 'Contribuinte'), ('exempt', 'Isento')], max_length=20, null=True, verbose_name='Tipo de Contribuinte')),
                ('state_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Limite de Crédito')),
                ('is_exempt', models.BooleanField(default=False, verbose_name='Isento de Impostos')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['cpf_cnpj'], name='partners_cu_cpf_cnp_3f8e3a_idx'), models.Index(fields=['company', 'name'], name='partners_cu_company_6375c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'cpf_cnpj'), name='unique_customer_cpf_cnpj_per_company')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo ou inativo.', verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('trading_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cpf_cnpj', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo de Pessoa')),
                ('partner_type', models.CharField(blank=True, choices=[('customer', 'Cliente'), ('supplier', 'Fornecedor')], max_length=10, null=True, verbose_name='Tipo de Parceiro')),
                ('tax_regime', models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('simples_excesso', 'Simples Nacional – Excesso sublimite'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=20, null=True, verbose_name='Regime Tributário')),
                ('tax_payer_type', models.CharField(blank=True, choices=[('non_taxpayer', 'Não Contribuinte'), ('taxpayer', 'Contribuinte'), ('exempt', 'Isento')], max_length=20, null=True, verbose_name='Tipo de Contribuinte')),
                ('state_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('bank_agency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência')),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta')),
                ('bank_pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX')),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Condições de Pagamento')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['cpf_cnpj'], name='partners_su_cpf_cnp_74c4a6_idx'), models.Index(fields=['company', 'name'], name='partners_su_company_235322_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'cpf_cnpj'), name='unique_supplier_cpf_cnpj_per_company')],
            },
        ),
    ]
