# Generated by Django 5.2.6 on 2025-11-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_customer_person_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
