# Generated by Django 5.2.6 on 2025-11-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_customer_address_supplier_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
