# Generated by Django 5.2.6 on 2025-11-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_customer_address_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Limite de Crédito'),
        ),
    ]
