# Generated by Django 5.2.6 on 2025-10-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_establishment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='cnpj',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='state_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
