# Generated by Django 5.2.6 on 2025-10-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_establishment_address_alter_establishment_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
