# Generated by Django 5.2.6 on 2025-10-09 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Permissão')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Código da Permissão')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships_company', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário da Conta'), ('admin', 'Administrador'), ('member', 'Membro')], default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='memberships_permissions', to='accounts.permission'),
        ),
    ]
