# Generated by Django 5.2.6 on 2025-10-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_permission_alter_membership_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='environment_default',
            field=models.CharField(choices=[('production', 'Produção'), ('homologation', 'Homologação')], default='production', max_length=20, verbose_name='Ambiente Padrão'),
        ),
    ]
