# Generated by Django 5.2.6 on 2025-11-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_establishment_environment_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='address',
        ),
    ]
