# Generated by Django 5.2.6 on 2025-11-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_establishment_address'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='core.address', verbose_name='Endereço'),
        ),
    ]
