# Generated by Django 5.2.6 on 2025-11-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_establishment_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
