# Generated by Django 5.2.6 on 2025-11-24 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abreviação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFiscalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo ou inativo.', verbose_name='Ativo')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=7, null=True, verbose_name='CEST')),
                ('cfop', models.CharField(max_length=4, verbose_name='CFOP Padrão')),
                ('origin', models.CharField(choices=[('0', 'Nacional'), ('1', 'Estrangeira - Importação direta'), ('2', 'Estrangeira - Mercado interno')], default='0', max_length=1, verbose_name='Origem da Mercadoria')),
                ('cst_icms', models.CharField(blank=True, max_length=3, null=True, verbose_name='CST ICMS')),
                ('cst_pis', models.CharField(blank=True, max_length=3, null=True, verbose_name='CST PIS')),
                ('cst_cofins', models.CharField(blank=True, max_length=3, null=True, verbose_name='CST COFINS')),
                ('icms_aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota ICMS')),
                ('pis_aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota PIS')),
                ('cofins_aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota COFINS')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Dados Fiscais do Produto',
                'verbose_name_plural': 'Dados Fiscais do Produto',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo ou inativo.', verbose_name='Ativo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Produto')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Barras')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Custo')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
                ('fiscal_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='inventory.productfiscaldata')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.unit')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
