# Generated by Django 5.2.6 on 2025-11-30 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_address'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o registro está ativo ou inativo.', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'name'], name='inventory_c_company_07f959_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_category_slug_per_company'),
        ),
    ]
