# Generated by Django 5.2.6 on 2025-11-30 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_address'),
        ('inventory', '0002_category_company_category_is_active_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria de Produto', 'verbose_name_plural': 'Categorias de Produto'},
        ),
        migrations.AddField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o registro está ativo ou inativo.', verbose_name='Ativo'),
        ),
    ]
