# Generated by Django 5.2.6 on 2025-12-01 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_options_unit_company_unit_is_active'),
        ('partners', '0007_supplier_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='partners.supplier', verbose_name='Fornecedor'),
        ),
    ]
